- name: Configure Bootcamp Environment 2017
  hosts: nodes
  become: True
  vars:
    inclide: vars.yml
  tasks:
    ### ssh config file modify
    - name: Enable password authentication ssh
      replace: >-
        dest='/etc/ssh/sshd_config'
        regexp='PasswordAuthentication no'
        replace='PasswordAuthentication yes'

    - name: Comment out ssh local configration
      lineinfile: >-
        dest='/etc/ssh/ssh_config'
        state=present
        regexp='SendEnv LANG LC_*'
        line='#SendEnv LANG LC_*'

    - name: Restart ssh Service
      service:
        name: ssh
        state: restarted

    ### Install Packages
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Service nginx enable
      service:
        name: nginx
        enabled: yes

    - name: Install php-fpm
      apt:
        name: php-fpm
        state: latest

    - name: Install mysql packages
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server
        - libmysqlclient-dev

    - name: Add apt repository
      apt_repository: repo='ppa:brightbox/ruby-ng'

    - name: Install other packages
      apt: name={{ item }} state=installed
      with_items:
        - ruby2.3
        - ruby2.3-dev
        - ruby-bundler
        - nodejs
        - libcurl4-openssl-dev
        - apache2-dev
        - libapr1-dev
        - libaprutil1-dev
        - libxml2
        - libxslt-dev
        - build-essential
        - patch
        - libmysqlclient-dev
        - libmagickwand-dev
        - imagemagick
        - libsqlite3-dev

    ### Set Application Code
    - name: Create Directory
      file:
        path: {{ apps.root }}
        state: directory
        owner: {{ apps.owner }}
        group: {{ apps.group }}
        mode: {{ apps.mode }}

    - name: Create User (bootcamp2017)
      user:
        name: {{ user.name }}
        groups: "{{ user.group }},sudo"
        shell: {{ user.shell }}
        password: {{ user.pass }}

    - name: Create bootcamp2017/.ssh directory
      file:
        path: /home/{{ user.name }}/.ssh
        state: directory
        owner: {{ user.name }}
        group: {{ user.group }}
        mode: 0755

    - name: Add authorized_keys to bootcamp2017
      copy:
        src: files/authorized_keys
        dest: /home/{{ user.name }}/.ssh/authorized_keys
        owner: {{ user.name }}
        group: {{ user.group }}
        mode: 0600

    - name: Copy mysql.cnf
      copy:
        src: files/my.cnf
        dest: /etc/mysql/my.cnf

    - name: Restart mysql
      service:
        name: mysql
        state: restarted

    - name: Git clone app code
      git:
        repo: {{ apps.repo }}
        dest: {{ apps.dir }}
        clone: yes
        force: yes

    - name: Change directory owner
      file:
        path: {{ apps.root }}
        owner: {{ apps.owner }}
        group: {{ apps.group }}
        recurse: yes

    ### Application Start Setting
    - name: Bundle Install
      shell: bundle install chdir={{ apps.dir }}

    - name: Rake DB Create (ENV=production)
      shell: rake db:create RAILS_ENV=production chdir={{ apps.dir }}

    - name: Rake DB Migrate (ENV=production)
      shell: rake db:migrate RAILS_ENV=production chdir={{ apps.dir }}

    - name: Copy unicorn.rb
      copy:
        src: files/unicorn.rb
        dest: "{{ apps.dir }}/config/unicorn.rb"

    - name: Copy init.d/unicorn (unicorn start shell)
      copy:
        src: files/unicorn
        dest: /etc/init.d/unicorn

    - name: Add execution right to unicorn
      file:
        path: /etc/init.d/unicorn
        mode: 0755

    - name: Reload daemon
      shell: systemctl daemon-reload

    - name: update unicorn
      shell: update-rc.d unicorn defaults

    - name: Copy nginx config file (/etc/nginx/sites-enabled/default)
      copy:
        src: files/sites-enabled_default
        dest: /etc/nginx/sites-enabled/default

    - name: Copy nginx config file (/etc/nginx/nginx.conf)
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted

    - name: Start unicorn
      shell: |
        result=$(/etc/init.d/unicorn status)
        starting="unicorn is running"
        stopping="unicorn is not running"

        if [ "${result}" = "${stopping}" ]; then
          /etc/init.d/unicorn start
        fi
