- name: Configure Bootcamp Environment 2017
  hosts: nodes
  #become: yes
  vars_files:
    - vars/vars.yml
  tasks:
    - include: tasks/basic_tasks.yml
    - include: tasks/install_imagemagick.yml
    - include: tasks/service_restart.yml
    - include: tasks/application_deploy_tasks.yml
